# Generated by Django 5.2.6 on 2025-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('counselling_type', models.CharField(choices=[('career', 'Career'), ('mental_health', 'Mental Health'), ('relationship', 'Relationship'), ('academic', 'Academic'), ('family', 'Family'), ('financial', 'Financial Wellness'), ('addiction', 'Addiction Support'), ('trauma', 'Trauma-informed')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
